# Generated by Django 2.1.2 on 2018-10-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date_committed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('repositories', models.ManyToManyField(through='contributors.Commit', to='repositories.Repository')),
            ],
        ),
        migrations.AddField(
            model_name='commit',
            name='contributories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.Contributor'),
        ),
        migrations.AddField(
            model_name='commit',
            name='repositories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.Repository'),
        ),
    ]
