# Generated by Django 2.1.2 on 2018-10-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='contributories',
            new_name='contributors',
        ),
    ]
