version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/productivity-ladder

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            export PIPENV_VENV_IN_PROJECT=~/productivity-ladder
            pipenv install --dev

      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: run static analysis
          command: |
            cd productivity_ladder && pipenv run flake8

      - run:
          name: run tests
          command: |
            cd productivity_ladder && pipenv run python manage.py test
